### ISSUE TITLE
Ошибка: [Errno 2] No such file or directory: 'google-chrome'

### ISSUE THREAD

**Issue by erm0nin** [Duff89/parser_avito#12]
Ошибка: [Errno 2] No such file or directory: 'google-chrome'

**Comment by Duff89** [comment]
Пожалуйста, сообщайте сразу больше информации об ошибке. Это позволит быстрее решить проблему
1) Установлен ли Chrome?
2) Как версия?
3) Что за операционная система?
4) Запускаете через графический интерфейс или из командной строки?

**Comment by erm0nin** [comment]
> Пожалуйста, сообщайте сразу больше информации об ошибке. Это позволит быстрее решить проблему
> 
> 1. Установлен ли Chrome?
> 2. Как версия?
> 3. Что за операционная система?
> 4. Запускаете через графический интерфейс или из командной строки?

1.установлен 
2.Версия 114.0.5735.133
3.macos
4.графический интерфейс

**Comment by Duff89** [comment]
Другое дело. Я не тестировал данный скрипт на macos, у меня его нет, но понимаю в чем причина:
 В файле parser.cls примерно 46 строку замените на:
 self.driver = uc.Chrome(version_main=114,options=options) 
Т.е напрямую пропишите версию Вашего Chrome

**Comment by erm0nin** [comment]
> 

теперь вылезла эта ошибка))
Ошибка: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)>

**Comment by erm0nin** [comment]
> Другое дело. Я не тестировал данный скрипт на macos, у меня его нет, но понимаю в чем причина: В файле parser.cls примерно 46 строку замените на: self.driver = uc.Chrome(version_main=114,options=options) Т.е напрямую пропишите версию Вашего Chrome

теперь вылезла эта ошибка))
Ошибка: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)>

**Comment by Duff89** [comment]
Решение из интернета:
перейдите в папку Macintosh HD > Applications > Python3.9 (или любую версию Python, которую вы используете) > дважды щелкните файл «Install Certificates.command»

> > Другое дело. Я не тестировал данный скрипт на macos, у меня его нет, но понимаю в чем причина: В файле parser.cls примерно 46 строку замените на: self.driver = uc.Chrome(version_main=114,options=options) Т.е напрямую пропишите версию Вашего Chrome
> 
> теперь вылезла эта ошибка)) Ошибка: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)>

Решение из интернета:
перейдите в папку Macintosh HD > Applications > Python3.9 (или любую версию Python, которую вы используете) > дважды щелкните файл «Install Certificates.command»

**Comment by erm0nin** [comment]
> > > Другое дело. Я не тестировал данный скрипт на macos, у меня его нет, но понимаю в чем причина: В файле parser.cls примерно 46 строку замените на: self.driver = uc.Chrome(version_main=114,options=options) Т.е напрямую пропишите версию Вашего Chrome
> > 
> > 
> > теперь вылезла эта ошибка)) Ошибка: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)>
> 
> Решение из интернета: перейдите в папку Macintosh HD > Applications > Python3.9 (или любую версию Python, которую вы используете) > дважды щелкните файл «Install Certificates.command»

огромноее спасибо все заработало!!
