### ISSUE TITLE
при установки requirements ошибка

### ISSUE THREAD

**Issue by Andy925925** [Duff89/parser_avito#18]
INFO: pip is looking at multiple versions of seleniumbase to determine which version is compatible with other requirements. This could take a while.
Collecting selenium==4.10.0 (from -r requirements.txt (line 67))
  Using cached selenium-4.10.0-py3-none-any.whl (6.7 MB)
Collecting requests==2.31.0 (from -r requirements.txt (line 62))
  Using cached requests-2.31.0-py3-none-any.whl (62 kB)
ERROR: Cannot install -r requirements.txt (line 62), -r requirements.txt (line 67), -r requirements.txt (line 68) and certifi==2022.12.7 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested certifi==2022.12.7
    requests 2.31.0 depends on certifi>=2017.4.17
    selenium 4.10.0 depends on certifi>=2021.10.8
    seleniumbase 4.15.3 depends on certifi>=2023.5.7

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

**Comment by Duff89** [comment]
Попробуйте удалить требование о версии:
В файле requirements.txt строка №7
Было: certifi==2022.12.7
Должно стать: certifi
Таким образом pip сам решит какую версию использовать
