### ISSUE TITLE
import customtkinter ModuleNotFoundError: No module named 'customtkinter'

### ISSUE THREAD

**Issue by Bankog86** [Duff89/parser_avito#24]
Установил все зависимости через pip, все модули которые выдавали ошибки из-за несовместимости версий - обновил до последних версий, даже этот customtkinter установлен последней версии, но при запуске кода выдает ошибку

Traceback (most recent call last):
  File "C:\PythonProject\parser_avito-master\parser_avito-master\AvitoParser.py", line 15, in <module>
    import customtkinter
ModuleNotFoundError: No module named 'customtkinter'

Что это может быть?

**Comment by Duff89** [comment]
> Установил все зависимости через pip, все модули которые выдавали ошибки из-за несовместимости версий - обновил до последних версий, даже этот customtkinter установлен последней версии, но при запуске кода выдает ошибку
> 
> Traceback (most recent call last): File "C:\PythonProject\parser_avito-master\parser_avito-master\AvitoParser.py", line 15, in import customtkinter ModuleNotFoundError: No module named 'customtkinter'
> 
> Что это может быть?

Используйте виртуальное окружение, а не глобальную установку зависимостей

**Comment by Genone22** [comment]
> Установил все зависимости через pip, все модули которые выдавали ошибки из-за несовместимости версий - обновил до последних версий, даже этот customtkinter установлен последней версии, но при запуске кода выдает ошибку
> 
> Traceback (most recent call last): File "C:\PythonProject\parser_avito-master\parser_avito-master\AvitoParser.py", line 15, in import customtkinter ModuleNotFoundError: No module named 'customtkinter'
> 
> Что это может быть?

Смогли решить проблему?

**Comment by Bankog86** [comment]
Да, просто запустил исполнение кода через терминал командой run

**Comment by spectr111** [comment]
> Да, просто запустил исполнение кода через терминал командой run

Объясни пж как, так же этот парсер не могу запустить

**Comment by Duff89** [comment]
> > Да, просто запустил исполнение кода через терминал командой run
> 
> Объясни пж как, так же этот парсер не могу запустить

В проекте есть readme, там написано как установить и запустить. Никаких особенностей нет.
Если Вы хотите, чтобы Вам реально помогли, то нужно писать подробнее: 
что делали, что устанавливали, какие ошибки может быть возникли, какая ОС стоит. Просто написать: не могу запустить - это к экстрасенсам

**Comment by spectr111** [comment]
https://github.com/DimaKalbfleysh/Avito этот парсер все таки, установил по дефу, ошибка ниже, ос Ubuntu 22.04.4 LTS, авито модуль устанавливал, переустанавливал, толку нет. python main.pyTraceback (most recent call last):  File "/home/stall/Avito/Avito/main.py", line 3, in <module>    from Avito.city import citiesModuleNotFoundError: No module named 'Avito' 21.04.2024, 16:16, "Serhey Davydovich" ***@***.***>:


Да, просто запустил исполнение кода через терминал командой run

Объясни пж как, так же этот парсер не могу запустить

В проекте есть readme, там написано как установить и запустить. Никаких особенностей нет.
Если Вы хотите, чтобы Вам реально помогли, то нужно писать подробнее:
что делали, что устанавливали, какие ошибки может быть возникли, какая ОС стоит. Просто написать: не могу запустить - это к экстрасенсам

**Comment by Duff89** [comment]
Так а я каким боком к  https://github.com/DimaKalbfleysh/Avito ?
