### ISSUE TITLE
Cannot install -r requirements.txt (line 69), -r requirements.txt (line 70) and trio-websocket==0.10.2 because these package versions have conflicting dependencies.

### ISSUE THREAD

**Issue by NikitaTsekh** [Duff89/parser_avito#25]
(venv) nikita@nikita-ubuntu:~/VS_Code_Projects/AvitoParser/parser_avito$ pip install -r requirements.txt
Collecting async-generator==1.10
  Using cached async_generator-1.10-py3-none-any.whl (18 kB)
Collecting attrs==23.1.0
  Using cached attrs-23.1.0-py3-none-any.whl (61 kB)
Collecting beautifulsoup4==4.12.2
  Using cached beautifulsoup4-4.12.2-py3-none-any.whl (142 kB)
Collecting behave==1.2.6
  Using cached behave-1.2.6-py2.py3-none-any.whl (136 kB)
Collecting blinker==1.6.2
  Using cached blinker-1.6.2-py3-none-any.whl (13 kB)
Collecting Brotli==1.0.9
  Using cached Brotli-1.0.9-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (2.7 MB)
Collecting certifi==2022.12.7
  Using cached certifi-2022.12.7-py3-none-any.whl (155 kB)
Collecting cffi==1.15.1
  Using cached cffi-1.15.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (441 kB)
Collecting chardet==5.1.0
  Using cached chardet-5.1.0-py3-none-any.whl (199 kB)
Collecting charset-normalizer==3.1.0
  Using cached charset_normalizer-3.1.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (199 kB)
Collecting click==8.1.3
  Using cached click-8.1.3-py3-none-any.whl (96 kB)
Collecting colorama==0.4.6
  Using cached colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Collecting cryptography==41.0.1
  Using cached cryptography-41.0.1-cp37-abi3-manylinux_2_28_x86_64.whl (4.3 MB)
Collecting cssselect==1.2.0
  Using cached cssselect-1.2.0-py2.py3-none-any.whl (18 kB)
Collecting customtkinter==5.2.0
  Using cached customtkinter-5.2.0-py3-none-any.whl (295 kB)
Collecting darkdetect==0.8.0
  Using cached darkdetect-0.8.0-py3-none-any.whl (9.0 kB)
Collecting exceptiongroup==1.1.1
  Using cached exceptiongroup-1.1.1-py3-none-any.whl (14 kB)
Collecting execnet==1.9.0
  Using cached execnet-1.9.0-py2.py3-none-any.whl (39 kB)
Collecting fasteners==0.18
  Using cached fasteners-0.18-py3-none-any.whl (18 kB)
Collecting filelock==3.12.2
  Using cached filelock-3.12.2-py3-none-any.whl (10 kB)
Collecting h11==0.14.0
  Using cached h11-0.14.0-py3-none-any.whl (58 kB)
Collecting h2==4.1.0
  Using cached h2-4.1.0-py3-none-any.whl (57 kB)
Collecting hpack==4.0.0
  Using cached hpack-4.0.0-py3-none-any.whl (32 kB)
Collecting hyperframe==6.0.1
  Using cached hyperframe-6.0.1-py3-none-any.whl (12 kB)
Collecting idna==3.4
  Using cached idna-3.4-py3-none-any.whl (61 kB)
Collecting importlib-metadata==6.6.0
  Using cached importlib_metadata-6.6.0-py3-none-any.whl (22 kB)
Collecting iniconfig==2.0.0
  Using cached iniconfig-2.0.0-py3-none-any.whl (5.9 kB)
Collecting jaraco.classes==3.2.3
  Using cached jaraco.classes-3.2.3-py3-none-any.whl (6.0 kB)
Collecting jeepney==0.8.0
  Using cached jeepney-0.8.0-py3-none-any.whl (48 kB)
Collecting jsonschema==4.17.3
  Using cached jsonschema-4.17.3-py3-none-any.whl (90 kB)
Collecting kaitaistruct==0.10
  Using cached kaitaistruct-0.10-py2.py3-none-any.whl (7.0 kB)
Collecting keyring==23.13.1
  Using cached keyring-23.13.1-py3-none-any.whl (37 kB)
Collecting loguru==0.7.0
  Using cached loguru-0.7.0-py3-none-any.whl (59 kB)
Collecting markdown-it-py==3.0.0
  Using cached markdown_it_py-3.0.0-py3-none-any.whl (87 kB)
Collecting mdurl==0.1.2
  Using cached mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Collecting more-itertools==9.1.0
  Using cached more_itertools-9.1.0-py3-none-any.whl (54 kB)
Collecting notifiers==1.3.3
  Using cached notifiers-1.3.3-py3-none-any.whl (43 kB)
Collecting outcome==1.2.0
  Using cached outcome-1.2.0-py2.py3-none-any.whl (9.7 kB)
Collecting packaging==23.1
  Using cached packaging-23.1-py3-none-any.whl (48 kB)
Collecting parameterized==0.9.0
  Using cached parameterized-0.9.0-py2.py3-none-any.whl (20 kB)
Collecting parse==1.19.0
  Using cached parse-1.19.0-py2.py3-none-any.whl (18 kB)
Collecting parse-type==0.6.0
  Using cached parse_type-0.6.0-py2.py3-none-any.whl (32 kB)
Collecting pdbp==1.4.0
  Using cached pdbp-1.4.0-py3-none-any.whl (17 kB)
Collecting platformdirs==3.5.3
  Using cached platformdirs-3.5.3-py3-none-any.whl (15 kB)
Collecting pluggy==1.0.0
  Using cached pluggy-1.0.0-py2.py3-none-any.whl (13 kB)
Collecting py==1.11.0
  Using cached py-1.11.0-py2.py3-none-any.whl (98 kB)
Collecting pyasn1==0.5.0
  Using cached pyasn1-0.5.0-py2.py3-none-any.whl (83 kB)
Collecting pycparser==2.21
  Using cached pycparser-2.21-py2.py3-none-any.whl (118 kB)
Collecting Pygments==2.15.1
  Using cached Pygments-2.15.1-py3-none-any.whl (1.1 MB)
Collecting pynose==1.4.5
  Using cached pynose-1.4.5-py3-none-any.whl (115 kB)
Collecting pyOpenSSL==23.2.0
  Using cached pyOpenSSL-23.2.0-py3-none-any.whl (59 kB)
Collecting pyotp==2.8.0
  Using cached pyotp-2.8.0-py3-none-any.whl (12 kB)
Collecting pyparsing==3.0.9
  Using cached pyparsing-3.0.9-py3-none-any.whl (98 kB)
Collecting pyrsistent==0.19.3
  Using cached pyrsistent-0.19.3-py3-none-any.whl (57 kB)
Collecting PySocks==1.7.1
  Using cached PySocks-1.7.1-py3-none-any.whl (16 kB)
Collecting pytest==7.3.2
  Using cached pytest-7.3.2-py3-none-any.whl (320 kB)
Collecting pytest-forked==1.6.0
  Using cached pytest_forked-1.6.0-py3-none-any.whl (4.9 kB)
Collecting pytest-html==2.0.1
  Using cached pytest_html-2.0.1-py2.py3-none-any.whl (15 kB)
Collecting pytest-metadata==3.0.0
  Using cached pytest_metadata-3.0.0-py3-none-any.whl (10 kB)
Collecting pytest-ordering==0.6
  Using cached pytest_ordering-0.6-py3-none-any.whl (4.6 kB)
Collecting pytest-rerunfailures==11.1.2
  Using cached pytest_rerunfailures-11.1.2-py3-none-any.whl (12 kB)
Collecting pytest-xdist==3.3.1
  Using cached pytest_xdist-3.3.1-py3-none-any.whl (41 kB)
Collecting PyYAML==6.0
  Using cached PyYAML-6.0-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (682 kB)
Collecting requests==2.31.0
  Using cached requests-2.31.0-py3-none-any.whl (62 kB)
Collecting requests-toolbelt==1.0.0
  Using cached requests_toolbelt-1.0.0-py2.py3-none-any.whl (54 kB)
Collecting rich==13.4.2
  Using cached rich-13.4.2-py3-none-any.whl (239 kB)
Collecting sbvirtualdisplay==1.2.0
  Using cached sbvirtualdisplay-1.2.0-py2.py3-none-any.whl (13 kB)
Collecting SecretStorage==3.3.3
  Using cached SecretStorage-3.3.3-py3-none-any.whl (15 kB)
Collecting selenium==4.10.0
  Using cached selenium-4.10.0-py3-none-any.whl (6.7 MB)
Collecting seleniumbase==4.15.3
  Using cached seleniumbase-4.15.3-py3-none-any.whl (526 kB)
Collecting six==1.16.0
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting sniffio==1.3.0
  Using cached sniffio-1.3.0-py3-none-any.whl (10 kB)
Collecting sortedcontainers==2.4.0
  Using cached sortedcontainers-2.4.0-py2.py3-none-any.whl (29 kB)
Collecting soupsieve==2.4.1
  Using cached soupsieve-2.4.1-py3-none-any.whl (36 kB)
Collecting tabcompleter==1.2.0
  Using cached tabcompleter-1.2.0-py3-none-any.whl (6.7 kB)
Collecting tomli==2.0.1
  Using cached tomli-2.0.1-py3-none-any.whl (12 kB)
Collecting tqdm==4.65.0
  Using cached tqdm-4.65.0-py3-none-any.whl (77 kB)
Collecting trio==0.22.0
  Using cached trio-0.22.0-py3-none-any.whl (384 kB)
Collecting trio-websocket==0.10.2
  Using cached trio_websocket-0.10.2-py3-none-any.whl (17 kB)
Collecting undetected-chromedriver==3.4.6
  Using cached undetected-chromedriver-3.4.6.tar.gz (61 kB)
  Preparing metadata (setup.py) ... done
Collecting urllib3==1.26.15
  Using cached urllib3-1.26.15-py2.py3-none-any.whl (140 kB)
Collecting websockets==11.0.2
  Using cached websockets-11.0.2-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (129 kB)
Collecting wsproto==1.2.0
  Using cached wsproto-1.2.0-py3-none-any.whl (24 kB)
Collecting zipp==3.15.0
  Using cached zipp-3.15.0-py3-none-any.whl (6.8 kB)
Collecting zstandard==0.21.0
  Using cached zstandard-0.21.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.7 MB)
Collecting urllib3[socks]<3,>=1.26
  Using cached urllib3-2.0.4-py3-none-any.whl (123 kB)
INFO: pip is looking at multiple versions of selenium to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of secretstorage to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of sbvirtualdisplay to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of rich to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of requests-toolbelt to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of requests to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of pyyaml to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of pytest-xdist to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of pytest-rerunfailures to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of pytest-ordering to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of pytest-metadata to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of pytest-html to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of pytest-forked to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of pytest to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of pysocks to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of pyrsistent to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of pyparsing to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of pyotp to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of pyopenssl to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of pynose to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of pygments to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of pycparser to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of pyasn1 to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of py to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of pluggy to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of platformdirs to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of pdbp to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of parse-type to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of parse to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of parameterized to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of packaging to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of outcome to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of notifiers to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of more-itertools to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of mdurl to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of markdown-it-py to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of loguru to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of keyring to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of kaitaistruct to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of jsonschema to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of jeepney to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of jaraco-classes to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of iniconfig to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of importlib-metadata to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of idna to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of hyperframe to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of hpack to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of h2 to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of h11 to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of filelock to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of fasteners to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of execnet to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of exceptiongroup to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of darkdetect to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of customtkinter to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of cssselect to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of cryptography to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of colorama to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of click to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of charset-normalizer to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of chardet to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of cffi to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of certifi to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of brotli to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of blinker to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of behave to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of beautifulsoup4 to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of attrs to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of <Python from Requires-Python> to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of async-generator to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install -r requirements.txt (line 69), -r requirements.txt (line 70) and trio-websocket==0.10.2 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested trio-websocket==0.10.2
    selenium 4.10.0 depends on trio-websocket~=0.9
    seleniumbase 4.15.3 depends on trio-websocket==0.10.3; python_version >= "3.7"

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflict

**Comment by Duff89** [comment]
Удалите из зависимостей trio-websocket, пусть pip сам решит, что ему устанавливать
