### ISSUE TITLE
Бан по IP v1.08 + Chrome 115

### ISSUE THREAD

**Issue by Autolocsia** [Duff89/parser_avito#26]
Все время версия 1.06 стабильно работает с Chrome 114
Версия 1.06 + Chrome 115 работало, но с предупреждением
Если установить 1.08 + Chrome 115 = с первого поиска бан по IP от Авито, просит ввести капчу. Проверил дома два интернета + облако. Причем, даже разгадав капчу через 1,2 поиска опять бан прилетает и потом капча становится вообще не пробиваемая.

![Снимок экрана от 2023-07-31 03-50-35](https://github.com/Duff89/parser_avito/assets/43119424/8a3df3cf-dae1-42cd-b542-ce456a8306ad)
![Снимок экрана от 2023-07-31 03-55-49](https://github.com/Duff89/parser_avito/assets/43119424/876ef2d2-ff61-418d-b2ab-074475e2c711)

**Comment by Autolocsia** [comment]
На облаке пришлось ip менять и заново 1.06 ставить с Chrome 114. Так работает прекрасно
![Снимок экрана от 2023-07-31 03-32-38](https://github.com/Duff89/parser_avito/assets/43119424/21209813-37c8-4d49-b7e4-c6e547de0fa9)
p.s. заметил, что при установке с Chrome 115 все равно драйвер 114 версии ставится, хоть и ошибки больше нет с просьбой обновится, может из-за этого Авито что-то не нравится

**Comment by Duff89** [comment]
Chrome 115 принес что-то слишком много проблем, пользуйтесь пока версией 114

**Comment by Duff89** [comment]
Вышла новая версия, обновитесь
