### ISSUE TITLE
После запуска скрипта AvitoParser.py появляется обрезанное окошко  которое не раздвинуть

### ISSUE THREAD

**Issue by NikitaTsekh** [Duff89/parser_avito#27]
![image](https://github.com/Duff89/parser_avito/assets/98738510/dd78aa7f-aa3d-4d7c-b78a-85e8b646fc12)

**Comment by Autolocsia** [comment]
+1 у меня на Ubuntu 22.04.2 LTS так же

**Comment by Duff89** [comment]
> ![image](https://user-images.githubusercontent.com/98738510/257605816-dd78aa7f-aa3d-4d7c-b78a-85e8b646fc12.png)

Видимо есть небольшие проблемы с tkinter, главное чтобы функционально работало сейчас. Остальное поправлю в следующем обновлении

**Comment by Duff89** [comment]
Вышла новая версия, обновитесь
