### ISSUE TITLE
Ограничение городов

### ISSUE THREAD

**Issue by NikitaTsekh** [Duff89/parser_avito#28]
Мне нужно спарсить с помощью вашего скрипта данные по одному городу - Краснодар. 
Я забил ссылку, скрипт стал собирать .csv файл. Но после того как объявления в Краснодаре закончились, он стал парсить другие, сначала соседние типа Сочи и Анапы, потом все дальше и дальше, в конце закончил Кемерово и Красноярском 
Можно ли ввести функцию ограничения по городам? Чтобы в других городах просто не искать?

**Comment by NikitaTsekh** [comment]
https://www.avito.ru/sochi/uslugi?q=услуги+инженера+пто

**Comment by Duff89** [comment]
Вышла новая версия и функция ограничения по городам добавлена. обновитесь
