### ISSUE TITLE
Что означает сообщение  Доступ ограничен: проблема с IP?

### ISSUE THREAD

**Issue by NikitaTsekh** [Duff89/parser_avito#29]
2023-08-01 21:23:34.541 | SUCCESS  | parser_cls:__parse_full_page:138 - Доступ ограничен: проблема с IP. 
Последние объявления будут без подробностей

**Comment by NikitaTsekh** [comment]
Спасибо за ваш труд, кофе вам отправил)

**Comment by Autolocsia** [comment]
Я так подозреваю та же проблема, что и я описал Бан по IP v1.08 + Chrome 115 #26
После обновления зависимостей и Хрома что-то сломалось и Авито ругается

**Comment by Duff89** [comment]
Я добавил в README информацию насчет версии хрома 115. Они там что-то поменяли, так что даже seleniumbase слегка поломался и выкатывал срочно новую версию.
Как будет время более тщательно посмотрю что к чему и обновлю скрипт

**Comment by Duff89** [comment]
Вышла новая версия, обновитесь
