### ISSUE TITLE
Есть ли возможность запустить это на Win 7 x64?

### ISSUE THREAD

**Issue by lp85d** [Duff89/parser_avito#33]
Ошибка https://www.python.org/ftp/python/3.11.4/python-3.11.4-amd64.exe
Ошибка настройки
Одна или несколько проблем привели к сбою настройки. Пожалуйста, устраните неполадки, а затем повторите попытку настройки. Для получения дополнительной информации смотрите файл журнала.
Для установки Python 3.11.4 (64-разрядная версия) требуется как минимум Windows 8.1 или Windows Server 2012
Визит python.org чтобы загрузить более раннюю версию Python.

**Comment by Duff89** [comment]
> Ошибка https://www.python.org/ftp/python/3.11.4/python-3.11.4-amd64.exe Ошибка настройки Одна или несколько проблем привели к сбою настройки. Пожалуйста, устраните неполадки, а затем повторите попытку настройки. Для получения дополнительной информации смотрите файл журнала. Для установки Python 3.11.4 (64-разрядная версия) требуется как минимум Windows 8.1 или Windows Server 2012 Визит python.org чтобы загрузить более раннюю версию Python.

Вот последняя версия python которая поддерживает windows 7 [https://www.python.org/downloads/release/python-3816/](https://www.python.org/downloads/release/python-3816/)

**Comment by lp85d** [comment]
Спасибо

**Comment by Duff89** [comment]
Вот видео по данной теме: https://youtu.be/OTzBZs84q3I
Больше ничем помочь не могу по данной теме
