### ISSUE TITLE
Два чат юзер айди, рассылка двум и более пользователям

### ISSUE THREAD

**Issue by STFU280** [Duff89/parser_avito#34]
Возможно ли как то в GUI парсера прописать два айди (телеграмма), что бы рассылка шла двум и более аккаунтам?

**Comment by Duff89** [comment]
> Возможно ли как то в GUI парсера прописать два айди (телеграмма), что бы рассылка шла двум и более аккаунтам?

В данной версии это не предусмотрено

**Comment by STFU280** [comment]
> В данной версии это не предусмотрено

А не могли бы реализовать данную функцию в будущем обновлении или опасаетесь что скрипт будут использовать не по назначению? А то хотя бы было бы два слота под рассылку двум людям, ибо приходится делать костыли что бы пересылать другому человеку.
