### ISSUE TITLE
Отсутствует вставка из буфера обмена

### ISSUE THREAD

**Issue by diirectshot** [Duff89/parser_avito#35]
Когда копирую адрес с браузера для вставки в url, ничего не происходит. Это должно так быть? Как фиксить?

**Comment by Genone22** [comment]
> Когда копирую адрес с браузера для вставки в url, ничего не происходит. Это должно так быть? Как фиксить?

**Для этого необходимо добавить следующий `выделенный `код**

class Window(customtkinter.CTk):
    def __init__(self):
        super().__init__()
        ...
       ` self.bind_all("<Key>", self.on_key_release, "+")`
        ...
   ```
 def on_key_release(self, event):
        ctrl = (event.state & 0x4) != 0
        if event.keycode == 88 and ctrl and event.keysym.lower() != "x":
            event.widget.event_generate("<<Cut>>")

        if event.keycode == 86 and ctrl and event.keysym.lower() != "v":
            event.widget.event_generate("<<Paste>>")

        if event.keycode == 67 and ctrl and event.keysym.lower() != "c":
            event.widget.event_generate("<<Copy>>")

        if event.keycode == 65 and ctrl and event.keysym.lower() != "a":
            event.widget.select_range(0, 'end')
```
        ...

Если возникнут вопросы обращайтесь.

**Comment by Duff89** [comment]
Вышла новая версия, обновитесь
