### ISSUE TITLE
Добавьте пожалуйста функционал

### ISSUE THREAD

**Issue by QA-Vlad** [Duff89/parser_avito#38]
Добрый вечер. Спасибо за интересный софт, но мне в нём очень не хватает функции ввода нескольких chat_id через запятую, дабы сообщения из бота видел еще и мой друг. Понимаю что "спасибо" тут не достаточно, посему отправил вам небольшое пожертвование за вашу работу. Заранее спасибо!

![image](https://github.com/Duff89/parser_avito/assets/112564119/40bc5150-9abb-46ed-a60b-8fd81bb9e547)

**Comment by Duff89** [comment]
> Добрый вечер. Спасибо за интересный софт, но мне в нём очень не хватает функции ввода нескольких chat_id через запятую, дабы сообщения из бота видел еще и мой друг. Понимаю что "спасибо" тут не достаточно, посему отправил вам небольшое пожертвование за вашу работу. Заранее спасибо!
> 
> ![image](https://user-images.githubusercontent.com/112564119/275907927-40bc5150-9abb-46ed-a60b-8fd81bb9e547.png)

За донат спасибо. В план уже поставил данный функционал

**Comment by MikeBelov** [comment]
Может легче создать группу с другом и ботом, в программе указать chat_id группы?

**Comment by QA-Vlad** [comment]
> Может легче создать группу с другом и ботом, в программе указать chat_id группы?
Нет. Не подходит для моей задумки. В прочем, кажись автор софта уже забил, так что ей не суждено реализоваться...

**Comment by Duff89** [comment]
Закрываю в связи с выходом новой версии. Функционал добавлен)
