### ISSUE TITLE
Кодировка текста в csv 

### ISSUE THREAD

**Issue by drweye** [Duff89/parser_avito#40]
При открытии файла не корректно отображалась кодировка текста, в коде изменил на utf-8-sig и кодировка отображается правильно. Совет прочитал на другом форуме.

**Comment by Duff89** [comment]
> При открытии файла не корректно отображалась кодировка текста, в коде изменил на utf-8-sig и кодировка отображается правильно. Совет прочитал на другом форуме.

Рад, что проблема решилась. Напишите, пожалуйста, какая у Вас операционная система

**Comment by drweye** [comment]
> > При открытии файла не корректно отображалась кодировка текста, в коде изменил на utf-8-sig и кодировка отображается правильно. Совет прочитал на другом форуме.
> 
> Рад, что проблема решилась. Напишите, пожалуйста, какая у Вас операционная система

Windows 10
