### ISSUE TITLE
Не работает на маке

### ISSUE THREAD

**Issue by Andrew90909** [Duff89/parser_avito#41]
Добрый день, запустил код на маке - получил пустое окно без кнопок = нет возможности запустить парсер. Подскажите, пожалуйста, как исправить? 
<img width="1399" alt="Снимок экрана 2024-01-03 в 01 29 37" src="https://github.com/Duff89/parser_avito/assets/64608591/ee7a9f09-de56-403d-ae9a-4ee400f4e891">

**Comment by Duff89** [comment]
> Добрый день, запустил код на маке - получил пустое окно без кнопок = нет возможности запустить парсер. Подскажите, пожалуйста, как исправить? <img alt="Снимок экрана 2024-01-03 в 01 29 37" width="1399" src="https://private-user-images.githubusercontent.com/64608591/293801293-ee7a9f09-de56-403d-ae9a-4ee400f4e891.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyODMwMzksIm5iZiI6MTcwNDI4MjczOSwicGF0aCI6Ii82NDYwODU5MS8yOTM4MDEyOTMtZWU3YTlmMDktZGU1Ni00MDNkLWFlOWEtNGVlNDAwZjRlODkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAzVDExNTIxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1ZTk0ZGNiMDg2Yzc1YzZkODY2N2M5OGU2MDdjZDk0YTc2YTdiMjJhNjNmOWYwZjFlZDAyZTc5Mjk4YzFjYWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oBIk_BdkAwHU6cthMfHDrXbTfRYcoCWbbLC2t2-gRu4">

У меня нет физической возможности проверить скрипт на маке (у меня только windows и linux), поэтому только предположу, что дело в библиотеке Tk. Попробуйте использовать другие версии данной библиотеки

**Comment by eltats** [comment]
попробуйте `brew install python-tk`

**Comment by 1scrooge** [comment]
@eltats не помогло, по крайней мере на М2 процессоре

**Comment by Mamontosik** [comment]
Под python3 на macbook запустилось, но дальше "парсинга" не ушло. Результатов парсинга в файле нет, а в окне логов ошибка
2024-03-18 14:41:51.020 | ERROR    | parser_cls:__paginator:54 - An error has been caught in function '__paginator', process 'MainProcess' (14339), thread 'Thread-1 (start_scraping)' (13013807104):

selenium.common.exceptions.TimeoutException: Message: script timeout
  (Session info: chrome=122.0.6261.129)

**Comment by dublife4all** [comment]
через pycharm заработал, но ровно один раз, потом я так понимаю баг с новой вкладкой всплыл, переустановил baseselenium как рекомендуется в ридми - не помогло. m1 проц

**Comment by Dazmond-ru** [comment]
Не отображался интерфейс при версии tkinter 8.5 при установке tkinter 8.6 интерфейс работает. python 3.7.17

**Comment by Duff89** [comment]
Закрываю в связи с выходом новой версии
