### ISSUE TITLE
В процессе считывания возникла ... как я понимаю ошибка

### ISSUE THREAD

**Issue by surgutandrey** [Duff89/parser_avito#44]
url = title.find_element(*LocatorAvito.URL).get_attribute("href")
          │     │             │            └ ('css selector', "[data-marker='item-title']")
          │     │             └ <class 'locator.LocatorAvito'>
          │     └ <function WebElement.find_element at 0x0000028E43522B60>
          └ <seleniumbase.undetected.webelement.WebElement (session="cb5c86a08f9621887be1e1cfaf527ff5", element="70A08F309A729EADBEED4650...

  File "D:\GitRepo\parser_avito\.venv\Lib\site-packages\selenium\webdriver\remote\webelement.py", line 178, in get_attribute
    attribute_value = self.parent.execute_script(
                      │    └ <property object at 0x0000028E43526750>
                      └ <seleniumbase.undetected.webelement.WebElement (session="cb5c86a08f9621887be1e1cfaf527ff5", element="70A08F309A729EADBEED4650...
  File "D:\GitRepo\parser_avito\.venv\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 408, in execute_script
    return self.execute(command, {"script": script, "args": converted_args})["value"]
           │    │       │                   │               └ [<seleniumbase.undetected.webelement.WebElement (session="cb5c86a08f9621887be1e1cfaf527ff5", element="70A08F309A729EADBEED465...
           │    │       │                   └ '/* getAttribute */return (function(){return (function(){var h=this||self;function aa(a){return"string"==typeof a}function ba...
           │    │       └ 'w3cExecuteScript'
           │    └ <function WebDriver.execute at 0x0000028E434F5620>
           └ <seleniumbase.undetected.Chrome (session="cb5c86a08f9621887be1e1cfaf527ff5")>
  File "D:\GitRepo\parser_avito\.venv\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 348, in execute
    self.error_handler.check_response(response)
    │    │             │              └ {'status': 500, 'value': '{"value":{"error":"script timeout","message":"script timeout\\n  (Session info: chrome=121.0.6167.1...
    │    │             └ <function ErrorHandler.check_response at 0x0000028E43555B20>
    │    └ <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x0000028E45E081A0>
    └ <seleniumbase.undetected.Chrome (session="cb5c86a08f9621887be1e1cfaf527ff5")>
  File "D:\GitRepo\parser_avito\.venv\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
          │               │        │       └ ['\tGetHandleVerifier [0x00007FF7CFE25E42+3538674]', '\t(No symbol) [0x00007FF7CFA44C02]', '\t(No symbol) [0x00007FF7CF8F599D...
          │               │        └ None
          │               └ 'script timeout\n  (Session info: chrome=121.0.6167.140)'
          └ <class 'selenium.common.exceptions.TimeoutException'>

selenium.common.exceptions.TimeoutException: Message: script timeout
  (Session info: chrome=121.0.6167.140)
Stacktrace:
        GetHandleVerifier [0x00007FF7CFE25E42+3538674]
        (No symbol) [0x00007FF7CFA44C02]
        (No symbol) [0x00007FF7CF8F599D]
        (No symbol) [0x00007FF7CF97CB92]
        (No symbol) [0x00007FF7CF95F0AA]
        (No symbol) [0x00007FF7CF97BDE3]
        (No symbol) [0x00007FF7CF95EE53]
        (No symbol) [0x00007FF7CF92F514]
        (No symbol) [0x00007FF7CF930631]
        GetHandleVerifier [0x00007FF7CFE56CAD+3738973]
        GetHandleVerifier [0x00007FF7CFEAC506+4089270]
        GetHandleVerifier [0x00007FF7CFEA4823+4057299]
        GetHandleVerifier [0x00007FF7CFB75C49+720121]
        (No symbol) [0x00007FF7CFA5126F]
        (No symbol) [0x00007FF7CFA4C304]
        (No symbol) [0x00007FF7CFA4C432]
        (No symbol) [0x00007FF7CFA3BD04]
        BaseThreadInitThunk [0x00007FFBF91A257D+29]
        RtlUserThreadStart [0x00007FFBF9E8AA58+40]

**Comment by Duff89** [comment]
> ```
> url = title.find_element(*LocatorAvito.URL).get_attribute("href")
>       │     │             │            └ ('css selector', "[data-marker='item-title']")
>       │     │             └ <class 'locator.LocatorAvito'>
>       │     └ <function WebElement.find_element at 0x0000028E43522B60>
>       └ <seleniumbase.undetected.webelement.WebElement (session="cb5c86a08f9621887be1e1cfaf527ff5", element="70A08F309A729EADBEED4650...
> ```
> 
> File "D:\GitRepo\parser_avito.venv\Lib\site-packages\selenium\webdriver\remote\webelement.py", line 178, in get_attribute attribute_value = self.parent.execute_script( │ └ <property object at 0x0000028E43526750> └ <seleniumbase.undetected.webelement.WebElement (session="cb5c86a08f9621887be1e1cfaf527ff5", element="70A08F309A729EADBEED4650... File "D:\GitRepo\parser_avito.venv\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 408, in execute_script return self.execute(command, {"script": script, "args": converted_args})["value"] │ │ │ │ └ [<seleniumbase.undetected.webelement.WebElement (session="cb5c86a08f9621887be1e1cfaf527ff5", element="70A08F309A729EADBEED465... │ │ │ └ '/* getAttribute */return (function(){return (function(){var h=this||self;function aa(a){return"string"==typeof a}function ba... │ │ └ 'w3cExecuteScript' │ └ <function WebDriver.execute at 0x0000028E434F5620> └ <seleniumbase.undetected.Chrome (session="cb5c86a08f9621887be1e1cfaf527ff5")> File "D:\GitRepo\parser_avito.venv\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 348, in execute self.error_handler.check_response(response) │ │ │ └ {'status': 500, 'value': '{"value":{"error":"script timeout","message":"script timeout\n (Session info: chrome=121.0.6167.1... │ │ └ <function ErrorHandler.check_response at 0x0000028E43555B20> │ └ <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x0000028E45E081A0> └ <seleniumbase.undetected.Chrome (session="cb5c86a08f9621887be1e1cfaf527ff5")> File "D:\GitRepo\parser_avito.venv\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response raise exception_class(message, screen, stacktrace) │ │ │ └ ['\tGetHandleVerifier [0x00007FF7CFE25E42+3538674]', '\t(No symbol) [0x00007FF7CFA44C02]', '\t(No symbol) [0x00007FF7CF8F599D... │ │ └ None │ └ 'script timeout\n (Session info: chrome=121.0.6167.140)' └ <class 'selenium.common.exceptions.TimeoutException'>
> 
> selenium.common.exceptions.TimeoutException: Message: script timeout (Session info: chrome=121.0.6167.140) Stacktrace: GetHandleVerifier [0x00007FF7CFE25E42+3538674] (No symbol) [0x00007FF7CFA44C02] (No symbol) [0x00007FF7CF8F599D] (No symbol) [0x00007FF7CF97CB92] (No symbol) [0x00007FF7CF95F0AA] (No symbol) [0x00007FF7CF97BDE3] (No symbol) [0x00007FF7CF95EE53] (No symbol) [0x00007FF7CF92F514] (No symbol) [0x00007FF7CF930631] GetHandleVerifier [0x00007FF7CFE56CAD+3738973] GetHandleVerifier [0x00007FF7CFEAC506+4089270] GetHandleVerifier [0x00007FF7CFEA4823+4057299] GetHandleVerifier [0x00007FF7CFB75C49+720121] (No symbol) [0x00007FF7CFA5126F] (No symbol) [0x00007FF7CFA4C304] (No symbol) [0x00007FF7CFA4C432] (No symbol) [0x00007FF7CFA3BD04] BaseThreadInitThunk [0x00007FFBF91A257D+29] RtlUserThreadStart [0x00007FFBF9E8AA58+40]

Ок, произошла ошибка, сервер не ответил вовремя. В чем вопрос? Или эта ошибка возникает теперь постоянно?

**Comment by surgutandrey** [comment]
Вчера я данную ошибку наблюдал раз 10

**Comment by Duff89** [comment]
Это парсинг защищенного сайта. Ошибки будут всегда, я могу их вообще скрыть для показа, но так будет сложнее разобраться в случае реального сбоя
