### ISSUE TITLE
Изменился путь  selector "[class*='item-description']"

### ISSUE THREAD

**Issue by fmfnjnf** [Duff89/parser_avito#5]
1. настройки:
[Avito]
url = https://www.avito.ru/moskva/tovary_dlya_kompyutera/monitory-ASgBAgICAUTGB4Bo?cd=1
chat_id = 
tg_token = 
num_ads = 1
freq = 2
keys = Мониторы, Монитор
max_price = 10000
min_price = 1000
2. Проработал менее часа
3. Ошибка было только эта
4. Скрипт продолжил работу, но ошибка никуда не исчезла.
2023-05-08 17:38:59.209 | ERROR    | __main__:__paginator:74 - An error has been                                                                                   caught in function '__paginator', process 'MainProcess' (142117), thread 'MainT                                                                                  hread' (140551600046080):
Traceback (most recent call last):

  File "/root/parser/parser_avito-master/parser_cls.py", line 208, in <module>
    ).parse()

  File "/root/parser/parser_avito-master/parser_cls.py", line 160, in parse
    self.__paginator()
    └ <__main__.AvitoParse object at 0x7fd4b6a4f5b0>

> File "/root/parser/parser_avito-master/parser_cls.py", line 74, in __paginator
    self.__parse_page()
    └ <__main__.AvitoParse object at 0x7fd4b6a4f5b0>

  File "/root/parser/parser_avito-master/parser_cls.py", line 100, in __parse_pa                                                                                  ge
    description = title.find_element(*LocatorAvito.DESCRIPTIONS).text
                  │     │             │            └ ('css selector', "[class*='                                                                                  item-description']")
                  │     │             └ <class 'locator.LocatorAvito'>
                  │     └ <function WebElement.find_element at 0x7fd4b71a1090>
                  └ <undetected_chromedriver.webelement.WebElement (session="8e4                                                                                  780bde71e07501846c8dafd2d46cb", element="9484AD4459801A6B5423AC83...

  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webele                                                                                  ment.py", line 426, in find_element
    return self._execute(Command.FIND_CHILD_ELEMENT, {"using": by, "value": valu                                                                                  e})["value"]
           │    │        │       │                             │            └ "[                                                                                  class*='item-description']"
           │    │        │       │                             └ 'css selector'
           │    │        │       └ 'findChildElement'
           │    │        └ <class 'selenium.webdriver.remote.command.Command'>
           │    └ <function WebElement._execute at 0x7fd4b71a1000>
           └ <undetected_chromedriver.webelement.WebElement (session="8e4780bde7                                                                                  1e07501846c8dafd2d46cb", element="9484AD4459801A6B5423AC83...
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webele                                                                                  ment.py", line 404, in _execute
    return self._parent.execute(command, params)
           │    │       │       │        └ {'using': 'css selector', 'value': "[                                                                                  class*='item-description']", 'id': '9484AD4459801A6B5423AC835E1F9AD5_element_477                                                                                  '}
           │    │       │       └ 'findChildElement'
           │    │       └ <function WebDriver.execute at 0x7fd4b71b1510>
           │    └ <undetected_chromedriver.Chrome (session="8e4780bde71e07501846                                                                                  c8dafd2d46cb")>
           └ <undetected_chromedriver.webelement.WebElement (session="8e4780bde7                                                                                  1e07501846c8dafd2d46cb", element="9484AD4459801A6B5423AC83...
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdri                                                                                  ver.py", line 440, in execute
    self.error_handler.check_response(response)
    │    │             │              └ {'status': 404, 'value': '{"value":{"err                                                                                  or":"no such element","message":"no such element: Unable to locate element: {\\"                                                                                  metho...
    │    │             └ <function ErrorHandler.check_response at 0x7fd4b73948b0                                                                                  >
    │    └ <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x7fd4                                                                                  b6a4fbe0>
    └ <undetected_chromedriver.Chrome (session="8e4780bde71e07501846c8dafd2d46cb                                                                                  ")>
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/errorh                                                                                  andler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
          │               │        │       └ ['#0 0x562e04be8133 <unknown>', '#1                                                                                   0x562e0491c966 <unknown>', '#2 0x562e049590dc <unknown>', '#3 0x562e04959211 <u                                                                                  nknown>', ...
          │               │        └ None
          │               └ 'no such element: Unable to locate element: {"method                                                                                  ":"css selector","selector":"[class*=\'item-description\']"}\n  (Session ...
          └ <class 'selenium.common.exceptions.NoSuchElementException'>

selenium.common.exceptions.NoSuchElementException: Message: no such element: Una                                                                                  ble to locate element: {"method":"css selector","selector":"[class*='item-descri                                                                                  ption']"}
  (Session info: chrome=113.0.5672.63)
Stacktrace:
#0 0x562e04be8133 <unknown>
#1 0x562e0491c966 <unknown>
#2 0x562e049590dc <unknown>
#3 0x562e04959211 <unknown>
#4 0x562e0494ee26 <unknown>
#5 0x562e04978bfd <unknown>
#6 0x562e0494ed13 <unknown>
#7 0x562e04978d9e <unknown>
#8 0x562e049911c7 <unknown>
#9 0x562e049789a3 <unknown>
#10 0x562e0494d46a <unknown>
#11 0x562e0494e55e <unknown>
#12 0x562e04ba7cae <unknown>
#13 0x562e04bab8fe <unknown>
#14 0x562e04bb4f20 <unknown>
#15 0x562e04bac923 <unknown>
#16 0x562e04b7fc0e <unknown>
#17 0x562e04bcfb08 <unknown>
#18 0x562e04bcfc97 <unknown>
#19 0x562e04be0113 <unknown>
#20 0x7f4da3007b43 <unknown>

--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/loguru/_logger.py", line 1251, i                                                                                  n catch_wrapper
    return function(*args, **kwargs)
  File "/root/parser/parser_avito-master/parser_cls.py", line 100, in __parse_pa                                                                                  ge
    description = title.find_element(*LocatorAvito.DESCRIPTIONS).text
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webele                                                                                  ment.py", line 426, in find_element
    return self._execute(Command.FIND_CHILD_ELEMENT, {"using": by, "value": valu                                                                                  e})["value"]
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webele                                                                                  ment.py", line 404, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdri                                                                                  ver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/errorh                                                                                  andler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Una                                                                                  ble to locate element: {"method":"css selector","selector":"[class*='item-descri                                                                                  ption']"}
  (Session info: chrome=113.0.5672.63)
Stacktrace:
#0 0x562e04be8133 <unknown>
#1 0x562e0491c966 <unknown>
#2 0x562e049590dc <unknown>
#3 0x562e04959211 <unknown>
#4 0x562e0494ee26 <unknown>
#5 0x562e04978bfd <unknown>
#6 0x562e0494ed13 <unknown>
#7 0x562e04978d9e <unknown>
#8 0x562e049911c7 <unknown>
#9 0x562e049789a3 <unknown>
#10 0x562e0494d46a <unknown>
#11 0x562e0494e55e <unknown>
#12 0x562e04ba7cae <unknown>
#13 0x562e04bab8fe <unknown>
#14 0x562e04bb4f20 <unknown>
#15 0x562e04bac923 <unknown>
#16 0x562e04b7fc0e <unknown>
#17 0x562e04bcfb08 <unknown>
#18 0x562e04bcfc97 <unknown>
#19 0x562e04be0113 <unknown>
#20 0x7f4da3007b43 <unknown>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/notifiers/logging.py", line 50,                                                                                   in emit
    self.provider.notify(raise_on_errors=True, **data)
  File "/usr/local/lib/python3.10/dist-packages/notifiers/core.py", line 303, in                                                                                   notify
    data = self._process_data(**kwargs)
  File "/usr/local/lib/python3.10/dist-packages/notifiers/core.py", line 235, in                                                                                   _process_data
    self._validate_data(data)
  File "/usr/local/lib/python3.10/dist-packages/notifiers/core.py", line 208, in                                                                                   _validate_data
    raise BadArguments(validation_error=msg, provider=self.name, data=data)
notifiers.exceptions.BadArguments: Error with sent data: 'An error has been caug                                                                                  ht in function \'__paginator\', process \'MainProcess\' (142117), thread \'MainT                                                                                  hread\' (140551600046080):\nTraceback (most recent call last):\n\n  File "/root/                                                                                  parser/parser_avito-master/parser_cls.py", line 208, in <module>\n    ).parse()\                                                                                  n\n  File "/root/parser/parser_avito-master/parser_cls.py", line 160, in parse\n                                                                                      self.__paginator()\n    -> <__main__.AvitoParse object at 0x7fd4b6a4f5b0>\n\                                                                                  n> File "/root/parser/parser_avito-master/parser_cls.py", line 74, in __paginato                                                                                  r\n    self.__parse_page()\n    -> <__main__.AvitoParse object at 0x7fd4b6a4f5b0                                                                                  >\n\n  File "/root/parser/parser_avito-master/parser_cls.py", line 100, in __par                                                                                  se_page\n    description = title.find_element(*LocatorAvito.DESCRIPTIONS).text\n                                                                                                    |     |             |            -> (\'css selector\', "[class                                                                                  *=\'item-description\']")\n                  |     |             -> <class \'loc                                                                                  ator.LocatorAvito\'>\n                  |     -> <function WebElement.find_eleme                                                                                  nt at 0x7fd4b71a1090>\n                  -> <undetected_chromedriver.webelement.                                                                                  WebElement (session="8e4780bde71e07501846c8dafd2d46cb", element="9484AD4459801A6                                                                                  B5423AC83...\n\n  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriv                                                                                  er/remote/webelement.py", line 426, in find_element\n    return self._execute(Co                                                                                  mmand.FIND_CHILD_ELEMENT, {"using": by, "value": value})["value"]\n           |                                                                                      |        |       |                             |            -> "[class*=\'ite                                                                                  m-description\']"\n           |    |        |       |                                                                                                               -> \'css selector\'\n           |    |        |       -> \'findChildElement\'\                                                                                  n           |    |        -> <class \'selenium.webdriver.remote.command.Command\                                                                                  '>\n           |    -> <function WebElement._execute at 0x7fd4b71a1000>\n                                                                                             -> <undetected_chromedriver.webelement.WebElement (session="8e4780bde71e0750                                                                                  1846c8dafd2d46cb", element="9484AD4459801A6B5423AC83...\n  File "/usr/local/lib/                                                                                  python3.10/dist-packages/selenium/webdriver/remote/webelement.py", line 404, in                                                                                   _execute\n    return self._parent.execute(command, params)\n           |    |                                                                                         |       |        -> {\'using\': \'css selector\', \'value\': "[class*=\'item                                                                                  -description\']", \'id\': \'9484AD4459801A6B5423AC835E1F9AD5_element_477\'}\n                                                                                             |    |       |       -> \'findChildElement\'\n           |    |       ->                                                                                   <function WebDriver.execute at 0x7fd4b71b1510>\n           |    -> <undetected_                                                                                  chromedriver.Chrome (session="8e4780bde71e07501846c8dafd2d46cb")>\n           ->                                                                                   <undetected_chromedriver.webelement.WebElement (session="8e4780bde71e07501846c8                                                                                  dafd2d46cb", element="9484AD4459801A6B5423AC83...\n  File "/usr/local/lib/python                                                                                  3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 440, in execute                                                                                  \n    self.error_handler.check_response(response)\n    |    |             |                                                                                                -> {\'status\': 404, \'value\': \'{"value":{"error":"no such element","                                                                                  message":"no such element: Unable to locate element: {\\\\"metho...\n    |    |                                                                                               -> <function ErrorHandler.check_response at 0x7fd4b73948b0>\n    |                                                                                      -> <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x7fd4b6a4fb                                                                                  e0>\n    -> <undetected_chromedriver.Chrome (session="8e4780bde71e07501846c8dafd                                                                                  2d46cb")>\n  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/re                                                                                  mote/errorhandler.py", line 245, in check_response\n    raise exception_class(me                                                                                  ssage, screen, stacktrace)\n          |               |        |       -> [\'#0                                                                                   0x562e04be8133 <unknown>\', \'#1 0x562e0491c966 <unknown>\', \'#2 0x562e049590dc                                                                                   <unknown>\', \'#3 0x562e04959211 <unknown>\', ...\n          |               |                                                                                          -> None\n          |               -> \'no such element: Unable to locate                                                                                   element: {"method":"css selector","selector":"[class*=\\\'item-description\\\']                                                                                  "}\\n  (Session ...\n          -> <class \'selenium.common.exceptions.NoSuchElem                                                                                  entException\'>\n\nselenium.common.exceptions.NoSuchElementException: Message: n                                                                                  o such element: Unable to locate element: {"method":"css selector","selector":"[                                                                                  class*=\'item-description\']"}\n  (Session info: chrome=113.0.5672.63)\nStacktra                                                                                  ce:\n#0 0x562e04be8133 <unknown>\n#1 0x562e0491c966 <unknown>\n#2 0x562e049590dc                                                                                   <unknown>\n#3 0x562e04959211 <unknown>\n#4 0x562e0494ee26 <unknown>\n#5 0x562e0                                                                                  4978bfd <unknown>\n#6 0x562e0494ed13 <unknown>\n#7 0x562e04978d9e <unknown>\n#8                                                                                   0x562e049911c7 <unknown>\n#9 0x562e049789a3 <unknown>\n#10 0x562e0494d46a <unkno                                                                                  wn>\n#11 0x562e0494e55e <unknown>\n#12 0x562e04ba7cae <unknown>\n#13 0x562e04bab                                                                                  8fe <unknown>\n#14 0x562e04bb4f20 <unknown>\n#15 0x562e04bac923 <unknown>\n#16 0                                                                                  x562e04b7fc0e <unknown>\n#17 0x562e04bcfb08 <unknown>\n#18 0x562e04bcfc97 <unkno                                                                                  wn>\n#19 0x562e04be0113 <unknown>\n#20 0x7f4da3007b43 <unknown>\n\n\n' is too lo                                                                                  ng
Call stack:
  File "/root/parser/parser_avito-master/parser_cls.py", line 208, in <module>
    ).parse()
  File "/root/parser/parser_avito-master/parser_cls.py", line 160, in parse
    self.__paginator()
  File "/root/parser/parser_avito-master/parser_cls.py", line 74, in __paginator
    self.__parse_page()
  File "/usr/local/lib/python3.10/dist-packages/loguru/_logger.py", line 1250, i                                                                                  n catch_wrapper
    with catcher:
  File "/usr/local/lib/python3.10/dist-packages/loguru/_logger.py", line 1217, i                                                                                  n __exit__
    logger._log(level, from_decorator, catch_options, message, (), {})
  File "/usr/local/lib/python3.10/dist-packages/loguru/_logger.py", line 2002, i                                                                                  n _log
    handler.emit(log_record, level_id, from_decorator, raw, colored_message)
  File "/usr/local/lib/python3.10/dist-packages/loguru/_handler.py", line 197, i                                                                                  n emit
    self._sink.write(str_record)
  File "/usr/local/lib/python3.10/dist-packages/loguru/_simple_sinks.py", line 5                                                                                  0, in write
    self._handler.handle(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 968, in handle
    self.emit(record)
  File "/usr/local/lib/python3.10/dist-packages/notifiers/logging.py", line 52,                                                                                   in emit
    self.handleError(record)
Message: 'An error has been caught in function \'__paginator\', process \'MainPr                                                                                  ocess\' (142117), thread \'MainThread\' (140551600046080):\nTraceback (most rece                                                                                  nt call last):\n\n  File "/root/parser/parser_avito-master/parser_cls.py", line                                                                                   208, in <module>\n    ).parse()\n\n  File "/root/parser/parser_avito-master/pars                                                                                  er_cls.py", line 160, in parse\n    self.__paginator()\n    -> <__main__.AvitoPa                                                                                  rse object at 0x7fd4b6a4f5b0>\n\n> File "/root/parser/parser_avito-master/parser                                                                                  _cls.py", line 74, in __paginator\n    self.__parse_page()\n    -> <__main__.Avi                                                                                  toParse object at 0x7fd4b6a4f5b0>\n\n  File "/root/parser/parser_avito-master/pa                                                                                  rser_cls.py", line 100, in __parse_page\n    description = title.find_element(*L                                                                                  ocatorAvito.DESCRIPTIONS).text\n                  |     |             |                                                                                              -> (\'css selector\', "[class*=\'item-description\']")\n                  |                                                                                       |             -> <class \'locator.LocatorAvito\'>\n                  |     ->                                                                                   <function WebElement.find_element at 0x7fd4b71a1090>\n                  -> <und                                                                                  etected_chromedriver.webelement.WebElement (session="8e4780bde71e07501846c8dafd2                                                                                  d46cb", element="9484AD4459801A6B5423AC83...\n\n  File "/usr/local/lib/python3.1                                                                                  0/dist-packages/selenium/webdriver/remote/webelement.py", line 426, in find_elem                                                                                  ent\n    return self._execute(Command.FIND_CHILD_ELEMENT, {"using": by, "value":                                                                                   value})["value"]\n           |    |        |       |                                                                                                               |            -> "[class*=\'item-description\']"\n           |    |        |                                                                                         |                             -> \'css selector\'\n           |    |                                                                                          |       -> \'findChildElement\'\n           |    |        -> <class \'selenium.w                                                                                  ebdriver.remote.command.Command\'>\n           |    -> <function WebElement._exe                                                                                  cute at 0x7fd4b71a1000>\n           -> <undetected_chromedriver.webelement.WebEl                                                                                  ement (session="8e4780bde71e07501846c8dafd2d46cb", element="9484AD4459801A6B5423                                                                                  AC83...\n  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remo                                                                                  te/webelement.py", line 404, in _execute\n    return self._parent.execute(comman                                                                                  d, params)\n           |    |       |       |        -> {\'using\': \'css select                                                                                  or\', \'value\': "[class*=\'item-description\']", \'id\': \'9484AD4459801A6B5423                                                                                  AC835E1F9AD5_element_477\'}\n           |    |       |       -> \'findChildEleme                                                                                  nt\'\n           |    |       -> <function WebDriver.execute at 0x7fd4b71b1510>\                                                                                  n           |    -> <undetected_chromedriver.Chrome (session="8e4780bde71e075018                                                                                  46c8dafd2d46cb")>\n           -> <undetected_chromedriver.webelement.WebElement                                                                                   (session="8e4780bde71e07501846c8dafd2d46cb", element="9484AD4459801A6B5423AC83..                                                                                  .\n  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/web                                                                                  driver.py", line 440, in execute\n    self.error_handler.check_response(response                                                                                  )\n    |    |             |              -> {\'status\': 404, \'value\': \'{"val                                                                                  ue":{"error":"no such element","message":"no such element: Unable to locate elem                                                                                  ent: {\\\\"metho...\n    |    |             -> <function ErrorHandler.check_resp                                                                                  onse at 0x7fd4b73948b0>\n    |    -> <selenium.webdriver.remote.errorhandler.Err                                                                                  orHandler object at 0x7fd4b6a4fbe0>\n    -> <undetected_chromedriver.Chrome (ses                                                                                  sion="8e4780bde71e07501846c8dafd2d46cb")>\n  File "/usr/local/lib/python3.10/dis                                                                                  t-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_respon                                                                                  se\n    raise exception_class(message, screen, stacktrace)\n          |                                                                                                 |        |       -> [\'#0 0x562e04be8133 <unknown>\', \'#1 0x562e0491c966                                                                                   <unknown>\', \'#2 0x562e049590dc <unknown>\', \'#3 0x562e04959211 <unknown>\', .                                                                                  ..\n          |               |        -> None\n          |               -> \'n                                                                                  o such element: Unable to locate element: {"method":"css selector","selector":"[                                                                                  class*=\\\'item-description\\\']"}\\n  (Session ...\n          -> <class \'selen                                                                                  ium.common.exceptions.NoSuchElementException\'>\n\nselenium.common.exceptions.No                                                                                  SuchElementException: Message: no such element: Unable to locate element: {"meth                                                                                  od":"css selector","selector":"[class*=\'item-description\']"}\n  (Session info:                                                                                   chrome=113.0.5672.63)\nStacktrace:\n#0 0x562e04be8133 <unknown>\n#1 0x562e0491c                                                                                  966 <unknown>\n#2 0x562e049590dc <unknown>\n#3 0x562e04959211 <unknown>\n#4 0x56                                                                                  2e0494ee26 <unknown>\n#5 0x562e04978bfd <unknown>\n#6 0x562e0494ed13 <unknown>\n                                                                                  #7 0x562e04978d9e <unknown>\n#8 0x562e049911c7 <unknown>\n#9 0x562e049789a3 <unk                                                                                  nown>\n#10 0x562e0494d46a <unknown>\n#11 0x562e0494e55e <unknown>\n#12 0x562e04b                                                                                  a7cae <unknown>\n#13 0x562e04bab8fe <unknown>\n#14 0x562e04bb4f20 <unknown>\n#15                                                                                   0x562e04bac923 <unknown>\n#16 0x562e04b7fc0e <unknown>\n#17 0x562e04bcfb08 <unk                                                                                  nown>\n#18 0x562e04bcfc97 <unknown>\n#19 0x562e04be0113 <unknown>\n#20 0x7f4da30                                                                                  07b43 <unknown>\n\n'
Arguments: ()

**Comment by fmfnjnf** [comment]
Спасибо

**Comment by fmfnjnf** [comment]
Здравствуйте, появилась ошибка с обращением к странице.
An error has been caught in function '__paginator', process 'MainProcess' (250780), thread 'MainThread' (140391046656000):
Traceback (most recent call last):

  File "/root/parser/parser_avito-master/parser_cls.py", line 208, in <module>
    ).parse()

  File "/root/parser/parser_avito-master/parser_cls.py", line 160, in parse
    self.__paginator()
    -> <__main__.AvitoParse object at 0x7faf54df6fe0>

> File "/root/parser/parser_avito-master/parser_cls.py", line 74, in __paginator
    self.__parse_page()
    -> <__main__.AvitoParse object at 0x7faf54df6fe0>

  File "/root/parser/parser_avito-master/parser_cls.py", line 97, in __parse_page
    titles = self.driver.find_elements(*LocatorAvito.TITLES)
             |    |      |              |            -> ('css selector', "[data-marker='item']")
             |    |      |              -> <class 'locator.LocatorAvito'>
             |    |      -> <function WebDriver.find_elements at 0x7faf5560a710>
             |    -> <undetected_chromedriver.Chrome (session="c481b457004252340f1a928edffba412")>
             -> <__main__.AvitoParse object at 0x7faf54df6fe0>

  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 861, in find_elements
    return self.execute(Command.FIND_ELEMENTS, {"using": by, "value": value})["value"] or []
           |    |       |       |                        |            -> "[data-marker='item']"
           |    |       |       |                        -> 'css selector'
           |    |       |       -> 'findElements'
           |    |       -> <class 'selenium.webdriver.remote.command.Command'>
           |    -> <function WebDriver.execute at 0x7faf55609480>
           -> <undetected_chromedriver.Chrome (session="c481b457004252340f1a928edffba412")>
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
    |    |             |              -> {'status': 500, 'value': '{"value":{"error":"unknown error","message":"unknown error: session deleted because of page crash\\...
    |    |             -> <function ErrorHandler.check_response at 0x7faf557ec820>
    |    -> <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x7faf54c2eb90>
    -> <undetected_chromedriver.Chrome (session="c481b457004252340f1a928edffba412")>
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
          |               |        |       -> ['#0 0x55a69a6d4133 <unknown>', '#1 0x55a69a4087f0 <unknown>', '#2 0x55a69a3f20c2 <unknown>', '#3 0x55a69a3f0b18 <unknown>', ...
          |               |        -> None
          |               -> 'unknown error: session deleted because of page crash\nfrom unknown error: cannot determine loading status\nfrom tab crashed\...
          -> <class 'selenium.common.exceptions.WebDriverException'>

selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: chrome=113.0.5672.92)
Stacktrace:
#0 0x55a69a6d4133 <unknown>
#1 0x55a69a4087f0 <unknown>
#2 0x55a69a3f20c2 <unknown>
#3 0x55a69a3f0b18 <unknown>
#4 0x55a69a3f12c2 <unknown>
#5 0x55a69a3fee8f <unknown>
#6 0x55a69a3fff32 <unknown>
#7 0x55a69a412a31 <unknown>
#8 0x55a69a47d348 <unknown>
#9 0x55a69a4649a3 <unknown>
#10 0x55a69a43946a <unknown>
#11 0x55a69a43a55e <unknown>
#12 0x55a69a693cae <unknown>
#13 0x55a69a6978fe <unknown>
#14 0x55a69a6a0f20 <unknown>
#15 0x55a69a698923 <unknown>
#16 0x55a69a66bc0e <unknown>
#17 0x55a69a6bbb08 <unknown>
#18 0x55a69a6bbc97 <unknown>
#19 0x55a69a6cc113 <unknown>
#20 0x7f4033626b43 <unknown>

**Comment by Duff89** [comment]
Это всё тоже самое. Меня интересует дальнейшая работа скрипта, после данной ошибки он продолжил свою работу (сразу же или на след. итерации)?

**Comment by fmfnjnf** [comment]
Да, продолжил, в таком случае можно убрать логи для того, чтобы не выводились ошибки?

**Comment by fmfnjnf** [comment]
Спасибо большое за помощь

**Comment by Duff89** [comment]
Баг в версии 1.05 исправлен

**Comment by HATABCH** [comment]
здравствуйте столкнулся с ошибкой, текст приложу ниже, версия последняя
