### ISSUE TITLE
Не работает из-за того, что авито блокирует IP

### ISSUE THREAD

**Issue by AdelGiniyatullin** [Duff89/parser_avito#50]
![Снимок экрана 2024-05-11 190801](https://github.com/Duff89/parser_avito/assets/28383607/9e37a234-65d8-4b78-bc56-3e61bedd96da)

**Comment by AdelGiniyatullin** [comment]
> Такая же тема, как то можно обойти?
 Обошёл, используя прокси

**Comment by Lushin415** [comment]
> > Такая же тема, как то можно обойти?
> > Обошёл, используя прокси

Можешь помочь, не могу понять как прикрутить прокси к данному парсеру?

**Comment by AdelGiniyatullin** [comment]
> > > Такая же тема, как то можно обойти?
> > > Обошёл, используя прокси
> 
> Можешь помочь, не могу понять как прикрутить прокси к данному парсеру?

![image](https://github.com/Duff89/parser_avito/assets/28383607/72944b74-65c5-4ca7-b29f-77cc0018b157)
В файле parser_cls.py в функцию SB передать proxy, как на скрине

**Comment by Lushin415** [comment]
Спасибо!

**Comment by MuseCat77** [comment]
Можно обойти заходя сначала на главную страницу, а потом на тот url, который нужен. При этом на главной все равно будет висеть плашка о блокировке по ip, но дальше пускать будет все равно  
![image](https://github.com/Duff89/parser_avito/assets/66839978/f06ab3d3-b460-4f94-8d45-17a2ea63eb1a)  
Таймаут поставил по приколу, может и без него будет работать. Спустя некоторое время главная страница стала грузиться как следует, можно не дожидаться ее загрузки.

**Comment by Lushin415** [comment]
https://github.com/Duff89/parser_avito/issues/45#issue-2120458534
А какие настройки используете? 
У меня периодически вылетает ошибка, как выше по ссылке, иногда парсер продолжает работать, а иногда перестаёт.

**Comment by Duff89** [comment]
Закрываю в связи с выходом новой версии
