### ISSUE TITLE
Версия 2.0, зависимости

### ISSUE THREAD

**Issue by Aazamandius** [Duff89/parser_avito#55]
Новая версия 2.0
При выполнении 
pip install -r requirements.txt

The conflict is caused by:
  flet 0.24.1 depends on packaging<24.0 and >=23.1 
  seleniumbase 4.32.5 depends on packaging>=24.1

**Comment by Duff89** [comment]
> Новая версия 2.0 При выполнении pip install -r requirements.txt
> 
> The conflict is caused by: flet 0.24.1 depends on packaging<24.0 and >=23.1 seleniumbase 4.32.5 depends on packaging>=24.1

Да, конфликт версий подтверждаю. Подправил этот момент немного костыльным способом, попробуйте: https://github.com/Duff89/parser_avito#%D1%83%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B0

**Comment by Aazamandius** [comment]
Теперь так

<img width="849" alt="Screenshot 2024-11-20 at 16 34 32" src="https://github.com/user-attachments/assets/6b5972c4-17d5-4594-8284-be025addd18e">

**Comment by Aazamandius** [comment]
Не совсем корректный скрин приложил, ниже
<img width="685" alt="Screenshot 2024-11-20 at 16 38 06" src="https://github.com/user-attachments/assets/8d0d7c7e-8ccb-4d15-b785-8e5eaacdedb7">

**Comment by olegon85** [comment]
На винде получил такую же ошибку, но после фикса у меня всё установилось правда на винде

**Comment by Aazamandius** [comment]
aaz@aaz-mint:~/Downloads/parser_avito-master$ pip list
Package                   Version
------------------------- --------------
apturl                    0.5.2
attrs                     24.2.0
beartype                  0.19.0
beautifulsoup4            4.12.3
behave                    1.2.6
blinker                   1.7.0
Brlapi                    0.8.5
Brotli                    1.1.0
certifi                   2024.8.30
chardet                   5.2.0
charset-normalizer        3.4.0
click                     8.1.6
colorama                  0.4.6
command-not-found         0.3
configobj                 5.0.8
cryptography              41.0.7
cssselect                 1.2.0
cupshelpers               1.0
customtkinter             5.2.2
darkdetect                0.8.0
dbus-python               1.3.2
defer                     1.0.6
deprecation               2.0.7
distro                    1.9.0
exceptiongroup            1.2.2
execnet                   2.1.1
eyed3                     0.9.7
fasteners                 0.19
filelock                  3.16.1
filetype                  1.2.0
flet                      0.1.65
flex                      6.14.1
h11                       0.14.0
httplib2                  0.20.4
idna                      3.10
ifaddr                    0.2.0
IMDbPY                    2021.4.18
iniconfig                 2.0.0
jsonpointer               3.0.0
jsonschema                4.23.0
jsonschema-specifications 2024.10.1
launchpadlib              1.11.0
lazr.restfulclient        0.14.6
lazr.uri                  1.0.6
libevdev                  0.5
loguru                    0.7.0
louis                     3.29.0
lxml                      5.2.1
Mako                      1.3.2.dev0
Markdown                  3.5.2
markdown-it-py            3.0.0
MarkupSafe                2.1.5
mdurl                     0.1.2
mutagen                   1.46.0
mycdp                     1.1.0
netaddr                   0.8.0
netifaces                 0.11.0
notifiers                 1.3.3
oauthlib                  3.2.2
onboard                   1.4.1
outcome                   1.3.0.post0
packaging                 24.2
PAM                       0.4.2
parameterized             0.9.0
parse                     1.20.2
parse_type                0.6.4
pdbp                      1.6.1
pexpect                   4.9.0
pillow                    10.2.0
pip                       24.3.1
platformdirs              4.3.6
pluggy                    1.5.0
psutil                    5.9.8
ptyprocess                0.7.0
py                        1.11.0
pyasyncore                1.0.2
pycairo                   1.25.1
pycryptodomex             3.20.0
pycups                    2.0.1
pycurl                    7.45.3
pyelftools                0.30
Pygments                  2.18.0
PyGObject                 3.48.2
PyICU                     2.12
pyinotify                 0.9.6
PyJWT                     2.7.0
PyNaCl                    1.5.0
pynose                    1.5.3
pyotp                     2.9.0
pyparsing                 3.1.1
pyparted                  3.12.0
pypng                     0.20231004.0
PySocks                   1.7.1
pytest                    8.3.3
pytest-html               2.0.1
pytest-metadata           3.1.1
pytest-ordering           0.6
pytest-rerunfailures      14.0
pytest-xdist              3.6.1
python-apt                2.7.7+ubuntu1
python-debian             0.1.49+ubuntu2
python-dotenv             1.0.1
python-gnupg              0.5.2
python-magic              0.4.27
python-xlib               0.33
pytz                      2024.1
pyudev                    0.24.0
pyxdg                     0.28
PyYAML                    6.0.2
qrcode                    7.4.2
referencing               0.35.1
repath                    0.9.0
repolib                   2.2.1
requests                  2.32.3
requests-file             1.5.1
rfc3987                   1.3.8
rich                      13.9.4
rpds-py                   0.21.0
sbvirtualdisplay          1.3.0
selenium                  4.26.1
seleniumbase              4.32.12
setproctitle              1.3.3
setuptools                75.5.0
six                       1.16.0
sniffio                   1.3.1
sortedcontainers          2.4.0
soupsieve                 2.6
strict-rfc3339            0.7
systemd-python            235
tabcompleter              1.4.0
tinycss2                  1.2.1
tldextract                3.1.2
trio                      0.27.0
trio-websocket            0.11.1
typing_extensions         4.12.2
ubuntu-drivers-common     0.0.0
ufw                       0.36.2
undetected-chromedriver   3.4.6
Unidecode                 1.3.8
urllib3                   2.0.7
validate_email            1.3
wadllib                   1.3.6
watchdog                  6.0.0
webencodings              0.5.1
websocket-client          1.8.0
websockets                14.1
wheel                     0.45.0
wsproto                   1.2.0
xdg                       5
xkit                      0.0.0
xlrd                      2.0.1
yt-dlp                    2024.4.9
aaz@aaz-mint:~/Downloads/parser_avito-master$

**Comment by Aazamandius** [comment]
aaz@aaz-mint:~/Downloads/parser_avito-master$ pip list
Package                   Version
------------------------- --------------
apturl                    0.5.2
attrs                     24.2.0
beartype                  0.19.0
beautifulsoup4            4.12.3
behave                    1.2.6
blinker                   1.7.0
Brlapi                    0.8.5
Brotli                    1.1.0
certifi                   2024.8.30
chardet                   5.2.0
charset-normalizer        3.4.0
click                     8.1.6
colorama                  0.4.6
command-not-found         0.3
configobj                 5.0.8
cryptography              41.0.7
cssselect                 1.2.0
cupshelpers               1.0
customtkinter             5.2.2
darkdetect                0.8.0
dbus-python               1.3.2
defer                     1.0.6
deprecation               2.0.7
distro                    1.9.0
exceptiongroup            1.2.2
execnet                   2.1.1
eyed3                     0.9.7
fasteners                 0.19
filelock                  3.16.1
filetype                  1.2.0
flet                      0.1.65
flex                      6.14.1
h11                       0.14.0
httplib2                  0.20.4
idna                      3.10
ifaddr                    0.2.0
IMDbPY                    2021.4.18
iniconfig                 2.0.0
jsonpointer               3.0.0
jsonschema                4.23.0
jsonschema-specifications 2024.10.1
launchpadlib              1.11.0
lazr.restfulclient        0.14.6
lazr.uri                  1.0.6
libevdev                  0.5
loguru                    0.7.0
louis                     3.29.0
lxml                      5.2.1
Mako                      1.3.2.dev0
Markdown                  3.5.2
markdown-it-py            3.0.0
MarkupSafe                2.1.5
mdurl                     0.1.2
mutagen                   1.46.0
mycdp                     1.1.0
netaddr                   0.8.0
netifaces                 0.11.0
notifiers                 1.3.3
oauthlib                  3.2.2
onboard                   1.4.1
outcome                   1.3.0.post0
packaging                 24.2
PAM                       0.4.2
parameterized             0.9.0
parse                     1.20.2
parse_type                0.6.4
pdbp                      1.6.1
pexpect                   4.9.0
pillow                    10.2.0
pip                       24.3.1
platformdirs              4.3.6
pluggy                    1.5.0
psutil                    5.9.8
ptyprocess                0.7.0
py                        1.11.0
pyasyncore                1.0.2
pycairo                   1.25.1
pycryptodomex             3.20.0
pycups                    2.0.1
pycurl                    7.45.3
pyelftools                0.30
Pygments                  2.18.0
PyGObject                 3.48.2
PyICU                     2.12
pyinotify                 0.9.6
PyJWT                     2.7.0
PyNaCl                    1.5.0
pynose                    1.5.3
pyotp                     2.9.0
pyparsing                 3.1.1
pyparted                  3.12.0
pypng                     0.20231004.0
PySocks                   1.7.1
pytest                    8.3.3
pytest-html               2.0.1
pytest-metadata           3.1.1
pytest-ordering           0.6
pytest-rerunfailures      14.0
pytest-xdist              3.6.1
python-apt                2.7.7+ubuntu1
python-debian             0.1.49+ubuntu2
python-dotenv             1.0.1
python-gnupg              0.5.2
python-magic              0.4.27
python-xlib               0.33
pytz                      2024.1
pyudev                    0.24.0
pyxdg                     0.28
PyYAML                    6.0.2
qrcode                    7.4.2
referencing               0.35.1
repath                    0.9.0
repolib                   2.2.1
requests                  2.32.3
requests-file             1.5.1
rfc3987                   1.3.8
rich                      13.9.4
rpds-py                   0.21.0
sbvirtualdisplay          1.3.0
selenium                  4.26.1
seleniumbase              4.32.12
setproctitle              1.3.3
setuptools                75.5.0
six                       1.16.0
sniffio                   1.3.1
sortedcontainers          2.4.0
soupsieve                 2.6
strict-rfc3339            0.7
systemd-python            235
tabcompleter              1.4.0
tinycss2                  1.2.1
tldextract                3.1.2
trio                      0.27.0
trio-websocket            0.11.1
typing_extensions         4.12.2
ubuntu-drivers-common     0.0.0
ufw                       0.36.2
undetected-chromedriver   3.4.6
Unidecode                 1.3.8
urllib3                   2.0.7
validate_email            1.3
wadllib                   1.3.6
watchdog                  6.0.0
webencodings              0.5.1
websocket-client          1.8.0
websockets                14.1
wheel                     0.45.0
wsproto                   1.2.0
xdg                       5
xkit                      0.0.0
xlrd                      2.0.1
yt-dlp                    2024.4.9
aaz@aaz-mint:~/Downloads/parser_avito-master$

**Comment by Aazamandius** [comment]
Мне пришлось принудительно сделать 
pip install flet --upgrade
тогда он проапгрейдил на flet-0.24.1

Но. тогда
aaz@aaz-mint:-/Downloads/parser_avito-master$ python3 AvitoParser.py
/home/aaz/. flet/bin/flet-0.24.1/flet/flet: error while loading shared libraries:
libmpv.so.1: cannot open shared object file: No such file or directory

но вероятно это уже моя проблема

**Comment by olegon85** [comment]
установил сейчас в контейнер ubuntu 22.04 с ноля. чистейший. всё что нужно поставил и работает. Так что работоспособность подтверждаю :)
