### ISSUE TITLE
Всегда загружается описание

### ISSUE THREAD

**Issue by olegon85** [Duff89/parser_avito#56]
Не обращает внимание на параметр need_more_info = 0 и всегда загружает описание

**Comment by Duff89** [comment]
уберите "ограничение по городу"

**Comment by olegon85** [comment]
а его и нет. не вписан в параметр никак. 
![avito14](https://github.com/user-attachments/assets/de4dc60c-d3f6-4684-a364-b63c26ab3d19)
вот все параметры в файле

**Comment by olegon85** [comment]
Еще есть один момент. Поиск запущен и работает, но то что я получаю выглядит по-разному:
И там есть описание. Скрин ниже:
![avito15](https://github.com/user-attachments/assets/ae7b230d-0fe0-418c-bb47-6e29693de7b7)
А то что пихает авито свои предложения которые не подходят по гео у же без описания :)
![avito16](https://github.com/user-attachments/assets/d34a3fd4-9ea5-44c2-924d-39380feb2942)

**Comment by Duff89** [comment]
Немного ввел в заблуждение. Описание парсится с основной страницы, т.е. в любом случае оно будет.

Но всё равно в коде была ошибка (при любых настройках включался режим \Больше информации\). Уже исправил

**Comment by olegon85** [comment]
К сожалению изменения не работают. Специально очистил папку, оставив только файл настроек и скопировал новые файлы из архива для чистоты эксперимента. Всеравно объявления приходят с описанием.

**Comment by Duff89** [comment]
> К сожалению изменения не работают. Специально очистил папку, оставив только файл настроек и скопировал новые файлы из архива для чистоты эксперимента. Всеравно объявления приходят с описанием.

Описание парсится с основной страницы, т.е. в любом случае оно будет! С отключенным режимом \доп. инфо\  не будут приходить: кол-во, просмотров, автор, дата публикации

**Comment by olegon85** [comment]
эххх... Можно как-то отключить любой вид описания? Можете подсказать что убрать в коде возможно. Просто в телегу иногда прилетают здоровенные портянки от которых глаза в разбег.

**Comment by Duff89** [comment]
![{46F1CAF9-151C-4334-B6DA-A9937C030AE2}](https://github.com/user-attachments/assets/30d7daa6-df71-451a-886c-efbf74531b96)
Конечно. В файле parser_cls.py закомментируйте строку 175, должно получиться как на картинке
