### ISSUE TITLE
Добавить в конфиги файлы coockie

### ISSUE THREAD

**Issue by ButovoButovo** [Duff89/parser_avito#57]
1. Во первых хочется выразить благодарность за твою работу
2.  Собственно, вопросы: 
- Как я понимаю, если ты не авторизован на Авито, часть элементов на странице скрыта, следоваться, чтобы парсились все необходимые элементы нужно авторизоваться. Авторизоваться можно подкладывая файлы coockie, либо своей УЗ (если не жалко), либо купленные. 
- Пагинация. На сколько я  понимаю, у авито выдача в 100 страниц, на странице в среднем 50 объявлений. Если нужно собрать информацию более чем по 5 000 объявлений,  при этом, кнопки "Далее" нет. Как будет работать парсер?

**Comment by ButovoButovo** [comment]
> > 1. Во первых хочется выразить благодарность за твою работу
> > 2. Собственно, вопросы:
> > 
> > 
> > * Как я понимаю, если ты не авторизован на Авито, часть элементов на странице скрыта, следоваться, чтобы парсились все необходимые элементы нужно авторизоваться. Авторизоваться можно подкладывая файлы coockie, либо своей УЗ (если не жалко), либо купленные.
> > * Пагинация. На сколько я  понимаю, у авито выдача в 100 страниц, на странице в среднем 50 объявлений. Если нужно собрать информацию более чем по 5 000 объявлений,  при этом, кнопки "Далее" нет. Как будет работать парсер?
> 
> 1. О каких скрытых элементах идет речь?
> 2. Никак не будет работать. Если попробовать на Авито перейти на страницу 102, то загрузится 2, для парсера поведение будет таким же

1. Как я понимаю, парсер не может разобрать элементы с полями "Просмотров" , "Дата Публикации", "Продавец", "Адрес" 
![image](https://github.com/user-attachments/assets/dd139885-ee00-4d70-8bd8-c67c17b5e3d3)

2. Как в таком случае поступать, если нужно собрать данные, к примеру по всей россии? Перебирать вручную регионы и настраивать фильтры и после этого подставлять ссылки в парсер?

**Comment by Duff89** [comment]
Кол-во просмотров, дата публикации, адрес и автор парсятся нормально, нужно только включить режим "Доп. информация".
PS: бывает не определяет название продавца, но это нужно селекторы подккоректировать

**Comment by ButovoButovo** [comment]
А по поводу пагинации?

**Comment by Duff89** [comment]
> А по поводу пагинации?

Можно вставлять несколько ссылок с разными фильтрами (к примеру по цене, по локации и т.д.). Другого варианта я сейчас не вижу. 
Можно это конечно всё автоматизировать, но я не думаю, что эта фича так будет востребована
