### ISSUE TITLE
Ошибка создания файла csv из-за ограничения длинны файла

### ISSUE THREAD

**Issue by olegon85** [Duff89/parser_avito#58]
Собственно наткнулся на такую проблему потому что использую много ключевых слов. Файл с таким длинным именем винда создать не может. на linux пока не пробовал.

**Comment by Duff89** [comment]
Интересный момент, не подумал, что такое может быть. 
Пропишите в строке 287 в parser_cls.py
вместо
title_file = "-".join(list(map(str.lower, self.keys_word))) 
напишите
title_file = "my_custom_title"
В следующей версии исправлю

**Comment by olegon85** [comment]
думаю будет круто если файл будет называтся каким-то образом, а уже внутри файла,  допустим первой строчкой ссылка, второй ключи, а потом объявы.

**Comment by olegon85** [comment]
> Интересный момент, не подумал, что такое может быть. Пропишите в строке 287 в parser_cls.py вместо title_file = "-".join(list(map(str.lower, self.keys_word))) напишите title_file = "my_custom_title" В следующей версии исправлю

В таком формате всё работает. Круто. :)
