### ISSUE TITLE
Парсинг разных товаров с разным ценовым дмапозоном

### ISSUE THREAD

**Issue by MorinCerber** [Duff89/parser_avito#59]
Большинство использует парсер чтобы искать товар ниже рынка, условно я ищу айфоны и прочую apple технику

Но не могу разобраться в настройки цены
Условно я ищу айфон 11 по цене до 14000р, а так же макбук по цене в 80000р 
То здесь либо айфоны 11 все будут попадаться, либо маки не будут

Что делать?

**Comment by Duff89** [comment]
> Большинство использует парсер чтобы искать товар ниже рынка, условно я ищу айфоны и прочую apple технику
> 
> Но не могу разобраться в настройки цены Условно я ищу айфон 11 по цене до 14000р, а так же макбук по цене в 80000р То здесь либо айфоны 11 все будут попадаться, либо маки не будут
> 
> Что делать?

Согласен, есть такая проблема\недоработка. 
Я это уже понял после релиза и это будет исправлено в одной из следующих версий. 
Скорее всего будет привязка сразу всех параметров к каждой отдельной ссылке, чтобы можно было максимально уточнять поисковый запрос. 
В данный момент, Вы можете запустить просто несколько парсеров одновременно. Тупо скопировать данный проект несколько раз, выйдет к примеру parser_avito1, parser_avito2, parser_avito3 и запускать каждый отдельно. Единственный минус, скорее всего придется использовать отдельный прокси для каждой копии

**Comment by MorinCerber** [comment]
> > Большинство использует парсер чтобы искать товар ниже рынка, условно я ищу айфоны и прочую apple технику
> > Но не могу разобраться в настройки цены Условно я ищу айфон 11 по цене до 14000р, а так же макбук по цене в 80000р То здесь либо айфоны 11 все будут попадаться, либо маки не будут
> > Что делать?
> 
> Согласен, есть такая проблема\недоработка. Я это уже понял после релиза и это будет исправлено в одной из следующих версий. Скорее всего будет привязка сразу всех параметров к каждой отдельной ссылке, чтобы можно было максимально уточнять поисковый запрос. В данный момент, Вы можете запустить просто несколько парсеров одновременно. Тупо скопировать данный проект несколько раз, выйдет к примеру parser_avito1, parser_avito2, parser_avito3 и запускать каждый отдельно. Единственный минус, скорее всего придется использовать отдельный прокси для каждой копии


Слушай, да ты ангел
А когда примерно планируешь выпускать обнову? 

Я тоже парсер создавал, но из за ошибок просто твой взял 
Но мой работал схожим образом, но была схожая функция как у тебя keys, но данный метод искал именно по названиям 
И поочередно выбирал, url номер 1 смотрит по названиям с keys номер 1 (По названиям) и ценой до номер 1

**Comment by Duff89** [comment]
В планах через неделю выпустить новую версию, но это неточно

**Comment by olegon85** [comment]
Я делаю всё это сейчас. Просто нужно принять что парсер парсит то что показывает авито, то что вы запрашиваете, а значит он вам показывает либо айфоны либо макбуки. Вы там работаете с авито, поэтому заставлять парсер искать универсально в одном месте кучу разных товаров нет смысла не тратьте на это время. 
Самый лучший вариант в текущей реализации это максимально уточнить параметры поиска, а потом на каждую ссылку запускать отдельный процесс. Ссылку для поиска вы формируете сами указывая параметры на сайте авито: модели айфонов, цены, и тд 
Я бы лучше поприсил автора реализовать реально нужные фичи, которых не хватает. А пожеланий прям куча :) Но кто я такой........ :)

**Comment by Duff89** [comment]
> Я бы лучше попросил автора реализовать реально нужные фичи, которых не хватает. А пожеланий прям куча :) Но кто я такой........ :)
Так пишите чего не хватает парсеру, может быть реализую

**Comment by Duff89** [comment]
> Большинство использует парсер чтобы искать товар ниже рынка, условно я ищу айфоны и прочую apple технику
> 
> Но не могу разобраться в настройки цены Условно я ищу айфон 11 по цене до 14000р, а так же макбук по цене в 80000р То здесь либо айфоны 11 все будут попадаться, либо маки не будут
> 
> Что делать?

Поправка. На самом деле проще сразу зашить цену в ссылку, т.е. на самом авито выбрать фильтр по цене, а в парсере указать максимальный диапазон (от 0 до 99999999). Поэтому смысла в изменении логики я уже не вижу
