### ISSUE TITLE
Ошибка ли это ? 

### ISSUE THREAD

**Issue by stocklow** [Duff89/parser_avito#60]
22:18:44 - 'charmap' codec can't encode character '\u2705' in position 302: character maps to <undefined>
22:18:50 - 'charmap' codec can't encode character '\u2705' in position 302: character maps to <undefined>

Также хочу добавить, что паршу я обьявления в своем городе, сам парсер работает исправно, вижу это по окну браузера, тестовое сообщение в тг приходит, но вот новые обьявление он не отправляет в телеграм

**Comment by Duff89** [comment]
> 22:18:44 - 'charmap' codec can't encode character '\u2705' in position 302: character maps to 22:18:50 - 'charmap' codec can't encode character '\u2705' in position 302: character maps to
> 
> Также хочу добавить, что паршу я обьявления в своем городе, сам парсер работает исправно, вижу это по окну браузера, тестовое сообщение в тг приходит, но вот новые обьявление он не отправляет в телеграм

в описании объявления содержаться какие эмодзи и скрипт не может их нормально обработать. Исправлю этот момент в следующей версии

**Comment by stocklow** [comment]
Видимо ошибка в том, что парсер парсит также и это сообщение 
![IMG_7358](https://github.com/user-attachments/assets/89263d64-488f-4bb9-a97b-fdab7529c698)

И не может идентифицировать этот символ

**Comment by Duff89** [comment]
исправлено в версии 2.1.0
https://github.com/Duff89/parser_avito/commit/b0c977baaaee9e5a800edc482951bf3cef9434fa
