### ISSUE TITLE
Увеличение скорости парсинга

### ISSUE THREAD

**Issue by olegon85** [Duff89/parser_avito#62]
Есть вариант увеличения скорости парсинга? 

Пишу личные пожелания. может кто дополнит. сильно не пинайте :)

**Comment by Duff89** [comment]
Да, варианты есть. Это всегда в приоритете

**Comment by Duff89** [comment]
реализовано в версии 2.1.0
https://github.com/Duff89/parser_avito/commit/b0c977baaaee9e5a800edc482951bf3cef9434fa
