### ISSUE TITLE
Добавить черный список ключевиков

### ISSUE THREAD

**Issue by olegon85** [Duff89/parser_avito#63]
В дополнение к белому списку, добавить черный список
Например при поиске iphone будут приходить и объявы "чехол для iphone" . Лично я использую черные списки больше чем белые.

Пишу личные пожелания. может кто дополнит. сильно не пинайте :)

**Comment by Duff89** [comment]
Звучит разумно. Подождём обсуждения

**Comment by Duff89** [comment]
реализовано в версии 2.1.0
https://github.com/Duff89/parser_avito/commit/b0c977baaaee9e5a800edc482951bf3cef9434fa

**Comment by olegon85** [comment]
Хотелось бы уточнить по отсечению объяв по черноу списку: "отсечение" происходит если слово встречается в заголовке, в тексте объявления или везде?

**Comment by Duff89** [comment]
Проверяет в название и описании
