### ISSUE TITLE
отображение изменения цены

### ISSUE THREAD

**Issue by olegon85** [Duff89/parser_avito#66]
Так как id каждого просмотренного объявления уже сохраняется, то рядом с  id сохранять и цену. Так будет возможность в будущем увидеть, что цена изменилась и прислать сообщение в котором будет оповещение об изменении цены

Пишу личные пожелания. может кто дополнит. сильно не пинайте :)

**Comment by Duff89** [comment]
Идея отличная. Будет реализовано

**Comment by Duff89** [comment]
реализовано в версии 2.1.0
https://github.com/Duff89/parser_avito/commit/b0c977baaaee9e5a800edc482951bf3cef9434fa
