### ISSUE TITLE
Контроль минимального количества просмотров

### ISSUE THREAD

**Issue by olegon85** [Duff89/parser_avito#67]
Не отправлять сообщения в телегу если у любого нового объявления просмотров больше  чем заданное
Часто запуская новый поиск по новой ссылке, вы первые 2 месяца будете получать много опубликованных заново объявлений. Если будет настройка что отправляется допустим только если меньше 20-30 просмотров, то будет считатся новым, но позволит получать объявления если хочется обойти парссером не одну только первую страницу, а все.

Пишу личные пожелания. может кто дополнит. сильно не пинайте :)

**Comment by Duff89** [comment]
Звучит разумно. Подождём обсуждения

**Comment by Duff89** [comment]
реализовано в версии 2.1.0
https://github.com/Duff89/parser_avito/commit/b0c977baaaee9e5a800edc482951bf3cef9434fa
