### ISSUE TITLE
Ошибка парсинга description

### ISSUE THREAD

**Issue by IPRepin** [Duff89/parser_avito#9]
При запуске часто выходит ошибка, что item-description не найден.
Собирать description можно так:
`DESCRIPTIONS = (By.CSS_SELECTOR, "[style*='webkit']")`
тестировалось на недвижимости.

**Comment by Duff89** [comment]
Можете привести пример url, где не находит  item-description?

**Comment by IPRepin** [comment]
У меня появлялась тут:
https://www.avito.ru/tuapse/kvartiry/prodam-ASgBAgICAUSSA8YQ

**Comment by Duff89** [comment]
В связи с выходом новой версии закрываю проблему
